name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: python ${{ matrix.python-version }} on ${{matrix.os}}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - {python-version: "3.10", os: ubuntu-latest}
          - {python-version: "3.11", os: ubuntu-latest}

    steps:
      - uses: actions/checkout@v2
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip
      - name: Linting
        run: |
          python -m unimport . --diff --check
          python -m isort . --diff --check-only --verbose
          python -m black . --diff --check --verbose
          python -m flake8 . --verbose
          python -m mypy . --verbose
      - name: Install albert
        run: |
          python -m pip install wheel
          python -m pip install .[dev,cse]
      - name: Run unit tests
        run: |
          python -m pip install git+https://github.com/edeprince3/pdaggerq.git@master
          python -m pip install pytest pytest-cov
          pytest --cov albert/
